name: Main Publish
on:
  push:
    branches:
      - '**'
      - '!**-noci'
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    env:
        MAVEN_USER: ${{ secrets.MAVEN_USER }}
        MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
        SIGN_KEY_ALIAS: ${{ secrets.SIGN_KEY_ALIAS }}
        SIGN_KEY_PASSWORD: ${{ secrets.SIGN_KEY_PASSWORD }}
        SIGN_KEYSTORE_PASSWORD: ${{ secrets.SIGN_KEYSTORE_PASSWORD }}
        SIGN_KEYSTORE_DATA: ${{ secrets.SIGN_KEYSTORE_DATA }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: 'adopt'
          cache: gradle
      - name: Build and Publish
        run: ./gradlew publish --stacktrace --no-daemon